name: Generate GitHub Contribution Grid Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # ◼ Create the folder(s) where snk will write its output:
      - name: Make sure dist/ exists
        run: mkdir -p dist

      - name: Generate snake SVG/GIF via snk
        uses: Platane/snk@v3
        with:
          github_user_name: daynoh
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            # (optional) a GIF:
            dist/github-snake.gif?color_snake=orange&color_dots=#c0ffc0,#80ff80,#40ff40,#00ff00,#00cc00
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
